trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '2.1.503'

- task: 'PowerShell@2'
  displayName: 'Install Build Tools'
  inputs:
    targetType: 'filePath'
    filePath: 'build/installAndUpdateTools.ps1'
    workingDirectory: 'build'

- task: 'PowerShell@2'
  displayName: 'Test, Build and Pack Releases'
  inputs:
    targetType: 'filePath'
    filePath: 'build/build.ps1'
    workingDirectory: 'build'

- task: 'PowerShell@2'
  displayName: 'Pack Pre-Releases'
  inputs:
    targetType: 'filePath'
    filePath: 'build/packForPreRelease.ps1'
    workingDirectory: 'build'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Test Code Coverages'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: 'coverage/coverage.cobertura.xml'
    reportDirectory: 'coverage'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: 'testResults/*.trx'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact Staging'
  inputs:
    pathtoPublish: 'artifacts'
    artifactName: 'artifacts'
