trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '2.1.503'

- task: 'PowerShell@2'
  displayName: 'Install Build Tools'
  inputs:
    targetType: 'filePath'
    filePath: 'build/installAndUpdateTools.ps1'
    workingDirectory: 'build'
    pwsh: false

- task: 'PowerShell@2'
  displayName: 'Test and Build the App'
  inputs:
    targetType: 'filePath'
    filePath: 'build/build.ps1'
    workingDirectory: 'build'
    pwsh: false

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: 'coverage/coverage.cobertura.xml'
    reportDirectory: 'coverage'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: 'testResults/*.trx'

-task: CopyFiles@2
  displayName: 'Copy Nuget Packages'
  inputs:
    contents: artifacts\**
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Nuget Packages'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'artifacts'
