trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '2.1.503'

- task: 'PowerShell@2'
  displayName: 'Install Build Tools'
  inputs:
    targetType: 'filePath'
    filePath: 'build/installAndUpdateTools.ps1'
    workingDirectory: 'build'
    pwsh: true

- task: 'PowerShell@2'
  displayName: 'Test and Build the App'
  inputs:
    targetType: 'filePath'
    filePath: 'build/build.ps1'
    workingDirectory: 'build'
    pwsh: true

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: 'coverage/coverage.cobertura.xml'
    reportDirectory: 'coverage'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: 'testResults/*.trx'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Nuget Packages'
  inputs:
    artifactName: 'artifacts'
    targetPath: 'artifacts'
